name: Deploy PR preview

on:
  pull_request_target:
    types:
      - labeled
      - synchronize
      - closed

concurrency: 
  group: preview-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  issues: write
  packages: write
  pull-requests: write
  pages: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'safe')
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: | 
          pip install mkdocs-material mkdocs-git-revision-date-localized-plugin mkdocs-macros-plugin

      - name: Build
        # builds to "site" directory by default
        run: |
          mkdocs build -f mkdocs.yml -d site

      - name: Deploy preview
        uses: ccarouge/pr-preview-action@v2
        with:
          source-dir: site